# K-Nearest Neighbors (K-NN)

## Importing the libraries

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [3]:
dataset = pd.read_csv('Social_Network_Ads.csv')
X = dataset.iloc[:, :-1].values #all rows and columns except last coloumn
y = dataset.iloc[:, -1].values
#dataset
#i.loc means integer location
X
#print(y)
#print(dataset)

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  57000],
       [    19,  76000],
       [    27,  58000],
       [    27,  84000],
       [    32, 150000],
       [    25,  33000],
       [    35,  65000],
       [    26,  80000],
       [    26,  52000],
       [    20,  86000],
       [    32,  18000],
       [    18,  82000],
       [    29,  80000],
       [    47,  25000],
       [    45,  26000],
       [    46,  28000],
       [    48,  29000],
       [    45,  22000],
       [    47,  49000],
       [    48,  41000],
       [    45,  22000],
       [    46,  23000],
       [    47,  20000],
       [    49,  28000],
       [    47,  30000],
       [    29,  43000],
       [    31,  18000],
       [    31,  74000],
       [    27, 137000],
       [    21,  16000],
       [    28,  44000],
       [    27,  90000],
       [    35,  27000],
       [    33,  28000],
       [    30,  49000],
       [    26,  72000],
       [    27,  31000],


## Splitting the dataset into the Training set and Test set

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [26]:
#print(X_train)
len(X_train)

320

In [27]:
#print(y_train)
len(y_train)

320

In [36]:
#print(X_test)
len(X_test)

100

In [5]:
print(y_test)
len(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1]


80

## Feature Scaling

In [29]:
#from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
#sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [30]:
print(X_train)

[[0.95238095 0.95555556]
 [0.97619048 0.5037037 ]
 [0.14285714 0.2962963 ]
 [0.19047619 0.14814815]
 [0.95238095 0.17037037]
 [0.57142857 0.48148148]
 [0.52380952 0.44444444]
 [0.97619048 0.85185185]
 [0.66666667 0.19259259]
 [0.54761905 0.33333333]
 [0.57142857 0.36296296]
 [0.45238095 0.97037037]
 [0.11904762 0.24444444]
 [0.16666667 0.13333333]
 [0.14285714 0.51111111]
 [0.21428571 0.6       ]
 [0.11904762 0.35555556]
 [0.71428571 0.13333333]
 [0.71428571 0.55555556]
 [0.57142857 0.65925926]
 [0.61904762 0.17777778]
 [0.33333333 0.77777778]
 [0.47619048 0.25925926]
 [0.33333333 0.88888889]
 [0.80952381 0.04444444]
 [0.83333333 0.65925926]
 [0.5        0.2       ]
 [0.47619048 0.34074074]
 [0.42857143 0.25925926]
 [0.42857143 0.35555556]
 [0.4047619  0.07407407]
 [0.4047619  0.25925926]
 [0.57142857 0.42962963]
 [0.69047619 0.25185185]
 [0.97619048 0.1037037 ]
 [0.73809524 0.37037037]
 [0.64285714 0.85925926]
 [0.30952381 0.54814815]
 [0.66666667 0.4962963 ]
 [0.69047619 0.26666667]


In [31]:
print(X_test)

[[0.28571429 0.53333333]
 [0.47619048 0.25925926]
 [0.4047619  0.44444444]
 [0.28571429 0.47407407]
 [0.4047619  0.25925926]
 [0.21428571 0.03703704]
 [0.30952381 0.        ]
 [0.42857143 0.95555556]
 [0.         0.39259259]
 [0.69047619 0.20740741]
 [0.28571429 0.25185185]
 [0.23809524 0.2962963 ]
 [0.45238095 0.2962963 ]
 [0.5        0.45925926]
 [0.04761905 0.52592593]
 [0.33333333 0.75555556]
 [0.45238095 0.45925926]
 [0.02380952 0.51851852]
 [0.88095238 0.85185185]
 [0.4047619  0.05185185]
 [0.4047619  0.23703704]
 [0.69047619 0.95555556]
 [0.54761905 0.26666667]
 [0.69047619 0.66666667]
 [0.11904762 0.0962963 ]
 [0.73809524 0.93333333]
 [0.23809524 0.53333333]
 [0.26190476 0.48148148]
 [0.45238095 0.34814815]
 [0.33333333 0.52592593]
 [0.07142857 0.54074074]
 [0.45238095 0.47407407]
 [0.92857143 0.33333333]
 [0.45238095 0.28148148]
 [0.14285714 0.31851852]
 [0.         0.27407407]
 [0.0952381  0.48888889]
 [0.38095238 0.20740741]
 [0.30952381 0.14074074]
 [0.73809524 0.15555556]


## Training the K-NN model on the Training set

In [32]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 3, metric = 'minkowski', p = 1)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3, p=1)

## Predicting a new result

In [33]:
print(classifier.predict(sc.transform([[55,125000]]))) # predicting a result for a customer whose age is 55 and income is 125000
print(classifier.predict(sc.transform ([[26,80000]])))

[1]
[0]


C:\Users\skuma\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\Users\skuma\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

## Predicting the Test set results

In [34]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
# here we are comparing the predicted label and actual label of the test records one be one
#y_pred is predicated label by the model and y_test is actaul label of the test record prsent in dataset
#y_pred

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]]


C:\Users\skuma\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


## Making the Confusion Matrix

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score,  precision_score,recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)
precision_score(y_test, y_pred)
#recall_score(y_test, y_pred)
#f1_score(y_test, y_pred)

[[55  3]
 [ 1 21]]


0.875